#!/usr/bin/perl

use strict;
use warnings;

use JSON;

use constant STAT_FILE => '/var/www/hsmty/blog/status.json';

my $op = shift @ARGV;
my $status = {};
my $cont = '';
my $fh;

if (! -r STAT_FILE) {
	die "Can't read the status file";
} elsif (! -w STAT_FILE) {
	die "Cant' write to the status file";
}

open($fh, '<', STAT_FILE) or die $!;

{
	local $/;
	$cont = <$fh>;
}

close $fh;

$status = decode_json($cont);

if (lc($op) eq 'open' and !$status->{open}) {
	$status->{open} = JSON::true;	
	savefile(STAT_FILE, $status);
} elsif (lc($op) eq 'close' and $status->{open}) {
	$status->{open} = JSON::false;	
	savefile(STAT_FILE, $status);
} 

sub savefile
{
	my ($filename, $status) = @_;
	$status->{lastchange} = time();
	open($fh, '>', $filename) or die $_;
	print $fh to_json($status);
	close $fh;
}
